import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNavWrapper from "@/components/navigation/BottomNavWrapper";
import TopNavWrapper from "@/components/navigation/TopNavWrapper";
import { CartProvider } from "@/context/CartContext";
import { PincodeProvider } from "@/context/PincodeContext";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <PincodeProvider>
            <TopNavWrapper />
            <div className="pb-16 md:pb-0">
              {children}
            </div>
            <BottomNavWrapper />
            <Toaster />
          </PincodeProvider>
        </CartProvider>
      </body>
    </html>
  );
}
