-- Migration: Add structured plan storage for Gymna AI
-- This table stores parsed JSON responses from AI (diet plans, workout plans, etc.)

-- Create the gymna_plan_data table
CREATE TABLE IF NOT EXISTS public.gymna_plan_data (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    chat_id uuid NOT NULL,
    message_id uuid NOT NULL,
    user_id uuid NOT NULL,
    plan_type text NOT NULL CHECK (plan_type = ANY (ARRAY['diet'::text, 'workout'::text, 'custom'::text])),
    plan_title text NOT NULL,
    raw_json jsonb NOT NULL,
    parsed_data jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT gymna_plan_data_pkey PRIMARY KEY (id),
    CONSTRAINT gymna_plan_data_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.gymna_chats(id) ON DELETE CASCADE,
    CONSTRAINT gymna_plan_data_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.gymna_messages(id) ON DELETE CASCADE,
    CONSTRAINT gymna_plan_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_gymna_plan_data_chat_id ON public.gymna_plan_data(chat_id);
CREATE INDEX IF NOT EXISTS idx_gymna_plan_data_user_id ON public.gymna_plan_data(user_id);
CREATE INDEX IF NOT EXISTS idx_gymna_plan_data_plan_type ON public.gymna_plan_data(plan_type);
CREATE INDEX IF NOT EXISTS idx_gymna_plan_data_created_at ON public.gymna_plan_data(created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.gymna_plan_data ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own plan data"
    ON public.gymna_plan_data
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own plan data"
    ON public.gymna_plan_data
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own plan data"
    ON public.gymna_plan_data
    FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own plan data"
    ON public.gymna_plan_data
    FOR DELETE
    USING (auth.uid() = user_id);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gymna_plan_data TO authenticated;
GRANT USAGE ON SCHEMA public TO authenticated;

-- Add comment for documentation
COMMENT ON TABLE public.gymna_plan_data IS 'Stores structured plan data (diet/workout) generated by Gymna AI in JSON format for easy retrieval and display';
